### ISSUE TITLE
BHoM missing from Dynamo Add-ons

### ISSUE THREAD

**Issue by BristolCAD** [BHoM/Dynamo_UI#318] opened 2023-02-03 12:52 UTC
Hi, apologies if this has been discussed elsewhere. I expect this is user error as oppose to a bug, but;

I have downloaded and installed BHoM to Revit 2023. The plugin loads in Revit, I have activated it. When I load Dynamo, BHoM is supposed to be in the bar on the left hand side under Add-ons but it is not present. I can manually load one or two of the dll files if I navigate to C:\ProgramData\BHoM, but most won't load.

I've also tried copying files to this location: C:\Users\USERNAME\AppData\Roaming\Dynamo\Dynamo Revit\2.13\packages but again, nothing loads. 

Hoping someone might be able to shed some light and many thanks.

Edit: Some more information:
Under this location C:\Users\USERNAME\AppData\Roaming\Dynamo\Dynamo Revit\2.13\packages all the BHoM package files (bin, extra, pkg.json) seem to be in the 2.3 folder rather than the 2.13. But moving the files to 2.13 just causes Dynamo to crash upon opening.

**Comment by FraserGreenroyd** [comment] 2023-08-24 18:12
Duplicate of #319

**Closed by FraserGreenroyd** 2023-08-24 18:12 UTC
Labels: type:question
